services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cheko_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5431:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      JDBC_URL: jdbc:postgresql://postgres:5432/cheko_db
      JDBC_USERNAME: admin
      JDBC_PASSWORD: password
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "88:80"
    depends_on:
      - backend