services:
  postgres:
    image: postgres:17.2-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5431:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      JDBC_URL: ${JDBC_URL}
      JDBC_USERNAME: ${JDBC_USERNAME}
      JDBC_PASSWORD: ${JDBC_PASSWORD}
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "88:80"
    depends_on:
      - backend
